server:
  port: 8081

spring:
  config.import: vault://mpcs/database,vault://mpcs/server.ssl
  cloud.vault:
    enabled: true
    authentication: CERT
    ssl:
      key-store: file:/home/user/projects/springboot-cloudvault-demo/vault-server/bash/work/client-cert.jks
      key-store-password: changeit
      key-store-type: JKS
      trust-store: file:/home/user/projects/springboot-cloudvault-demo/vault-server/bash/work/keystore.jks
      trust-store-password: changeit
      trust-store-type: JKS
    uri: https://localhost:8200